// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".

/**
 * Datadog SLO 1.1.0
 */
export interface DatadogSLOProps {
  readonly creator?: SloCreator;
  /**
   * Description of the slo
   */
  readonly description?: string;
  /**
   * A list of (up to 20) monitor groups that narrow the scope of a monitor service level objective.
   */
  readonly groups?: string[];
  /**
   * ID of the slo
   */
  readonly id?: string;
  /**
   * A list of monitor ids that defines the scope of a monitor service level objective. Required if type is monitor.
   */
  readonly monitorIds?: number[];
  /**
   * Name of the slo
   */
  readonly name?: string;
  readonly query?: Query;
  /**
   * Tags associated with the slo
   */
  readonly tags?: string[];
  readonly thresholds?: Threshold[];
  /**
   * The type of the slo
   */
  readonly type?: "monitor" | "metric";
  /**
   * Date of creation of the slo
   */
  readonly created?: string;
  /**
   * Date of deletion of the slo
   */
  readonly deleted?: string;
  /**
   * Date of modification of the slo
   */
  readonly modified?: string;
}
export interface SloCreator {
  /**
   * Name of the creator of the slo
   */
  readonly name?: string;
  /**
   * Handle of the creator of the slo
   */
  readonly handle?: string;
  /**
   * Email of the creator of the slo
   */
  readonly email?: string;
}
export interface Query {
  /**
   * A Datadog metric query for total (valid) events.
   */
  readonly numerator?: string;
  /**
   * A Datadog metric query for good events.
   */
  readonly denominator?: string;
}
export interface Threshold {
  /**
   * The target value for the service level indicator within the corresponding timeframe.
   */
  readonly target?: number;
  /**
   * A string representation of the target that indicates its precision.(e.g. 98.00)
   */
  readonly targetDisplay?: string;
  /**
   * The SLO time window options. Allowed enum values: 7d,30d,90d
   */
  readonly timeframe?: "7d" | "30d" | "90d";
  /**
   * The warning value for the service level objective.
   */
  readonly warning?: number;
  /**
   * A string representation of the warning target.(e.g. 98.00)
   */
  readonly warningDisplay?: string;
}
