// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".

/**
 * Datadog Dashboard 2.1.0
 */
export interface DatadogDashboardProps {
  /**
   * ID of the dashboard
   */
  readonly id?: string;
  /**
   * Url of the dashboard
   */
  readonly url?: string;
  /**
   * JSON string of the dashboard definition
   */
  readonly dashboardDefinition?: string;
}
